name: Deploy
# site:
#   use_directory_urls: false
#   siteUrl: https://github.com/kakajun/vue3-flipbook
#   site_url: https://github.com/kakajun/vue3-flipbook
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install and Build 🔧
        run: |
          bun i
          bun run build
      - name: Build Storybook 💪
        run: bun run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/storybook/storybook-static # The folder the action should deploy.
          workspace: 'main'
          target-folder: 'gh-pages' # 放在1X目录下
      # - name: Set Git user
      #   run: |
      #     git config --global user.email "253495832.com"
      #     git config --global user.name "kakajun"
      # - name: Deploy Storybook 🔥
      #   run: bun run deploy-storybook
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_SECRET_TOKEN }}
      - name: publish 🚀
        run: node publish.js
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
