name: Deploy

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install and Build 🔧
        run: |
          bun i
          bun run build
      - name: Build Storybook 💪
        run: bun run build-storybook
      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/storybook/storybook-static
      # - name: Set Git user
      #   run: |
      #     git config --global user.email "253495832.com"
      #     git config --global user.name "kakajun"
      # - name: Deploy Storybook 🔥
      #   run: bun run deploy-storybook
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_SECRET_TOKEN }}
      - name: publish 🚀
        run: node publish.js
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
