name: Deploy
# site:
#   use_directory_urls: false
#   siteUrl: https://github.com/kakajun/vue3-flipbook
#   site_url: https://github.com/kakajun/vue3-flipbook
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - run: bun run build:storybook
      - run: bun run deploy:storybook
      - run: node publish.js
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_SECRET_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
